name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Multiline
        run: |
         echo This demo file shows a
         echo ${{secrets.MY_NAME}} | sed 's/./& /g'
         echo very basic and easy-to-understand workflow. 